#!/usr/bin/env bash
# Runs EVERY check from a clean tree and writes docs/VERIFICATION.md from the real output.
# Nothing in the report is typed by hand: counts come from parsing the tools' own output.
# Takes ~8-10 minutes. Use FUZZ_ITERS=n to change the fuzz budget (default 200000 per target).
set -uo pipefail
cd "$(dirname "$0")/.."
FUZZ_ITERS=${FUZZ_ITERS:-200000}
LOG=$(mktemp -d); trap 'rm -rf "$LOG"' EXIT
R=docs/VERIFICATION.md
declare -A RES DET
run() { # key description cmd...
    local key=$1; shift; local desc=$1; shift
    echo ">> $desc" >&2
    if "$@" > "$LOG/$key.log" 2>&1; then RES[$key]=PASS; else RES[$key]=FAIL; fi
    echo "   ${RES[$key]}" >&2
}
ver() { "$@" 2>&1 | head -1; }

run build    "clean build (make clean && make all)"          bash -c 'make clean >/dev/null 2>&1; make all 2>&1'
DET[build]="warnings-as-errors build; $(grep -c 'warning' "$LOG/build.log" || true) warnings in log"
run unit     "unit tests (ASan+UBSan)"                       make -s unit
DET[unit]=$(grep -E '^unit tests:' "$LOG/unit.log" | tail -1)
run lint     "static analysis (cppcheck + clang-tidy)"       scripts/static_analysis.sh
DET[lint]="$(grep -E '^(cppcheck|clang-tidy): clean' "$LOG/lint.log" | tr '\n' ' ')"
run fuzz     "sanitizer mutation fuzzing x$FUZZ_ITERS"       scripts/fuzz_dtb.sh "$FUZZ_ITERS" 1
DET[fuzz]="$(grep -E '^fuzz ' "$LOG/fuzz.log" | tr '\n' ';')"
RESULTS="$LOG/integ.tsv"; export RESULTS; : > "$RESULTS"
run integ    "QEMU integration / fault-injection suite"      tests/integration/run_qemu_tests.sh
DET[integ]=$(grep -E '^integration:' "$LOG/integ.log" | tail -1)
run repro    "reproducible build (same keys / different root key)" scripts/repro_check.sh
DET[repro]="$(grep -E '^(A|B):' "$LOG/repro.log" | tr '\n' ';')"
make -s all >/dev/null 2>&1      # repro leaves the build in the 'different key' state; rebuild with the real keys
run manifest "signed manifest sign+verify"                   make -s manifest
DET[manifest]="$(grep -E 'VERIFY OK|match the files' "$LOG/manifest.log" | tr '\n' ';')"
run sbom     "SBOM generate + validate (spdx-tools)"         make -s sbom
DET[sbom]="$(tail -1 "$LOG/sbom.log")"
run gdb      "scripted GDB session"                          bash -c 'scripts/gdb_demo.sh > docs/gdb-session.txt 2>&1 && grep -q "Breakpoint 1, qv_image_parse" docs/gdb-session.txt && grep -q "res->hash" docs/gdb-session.txt'
DET[gdb]="$(grep -cE '^Breakpoint [0-9]+,' docs/gdb-session.txt) breakpoint hits, transcript docs/gdb-session.txt"
run tcb      "TCB report"                                    make -s tcb
python3 scripts/tcb_report.py > docs/tcb-report.md 2>/dev/null || true
run boot     "default QEMU boot reaches SECURE BOOT SUCCESS" bash -c 'cp build/flash.img.pflash build/run.pflash; PFLASH=build/run.pflash timeout 20 scripts/run_qemu.sh | tr -d "\r" | tee build/boot.log | grep -q "SECURE BOOT SUCCESS"'

{
echo "# QVault verification report"
echo
echo "_Generated by \`scripts/verify_all.sh\` from the real output of each command. Re-run it to refresh. Nothing here is hand-typed._"
echo
echo "- Commit: \`$(git rev-parse --short HEAD 2>/dev/null || echo uncommitted)\`  (working tree $(git diff --quiet 2>/dev/null && echo clean || echo 'has uncommitted changes'))"
echo "- Host: $(uname -srm)"
echo "- Tools: $(ver aarch64-linux-gnu-gcc --version) | $(ver qemu-system-aarch64 --version) | $(ver dtc --version) | cppcheck $(cppcheck --version | awk '{print $2}') | $(ver clang-tidy --version | head -1) | $(ver gdb-multiarch --version)"
echo
echo "| Check | Result | Evidence (from the tool's own output) |"
echo "|---|---|---|"
for k in build unit lint fuzz integ repro manifest sbom gdb tcb boot; do
  echo "| $k | **${RES[$k]}** | ${DET[$k]:-see log} |"
done
echo
echo "## Integration scenarios (each boots QEMU on a fresh flash+pflash copy)"
echo
echo "| Result | Scenario |"
echo "|---|---|"
while IFS=$'\t' read -r r n; do echo "| $r | $n |"; done < "$RESULTS"
echo
echo "## Reproducibility detail"
echo '```'; cat "$LOG/repro.log"; echo '```'
echo
echo "## Default boot output"
echo '```'; cat build/boot.log 2>/dev/null; echo '```'
} > "$R"

echo; echo "wrote $R"
fails=0; for k in "${!RES[@]}"; do [ "${RES[$k]}" = PASS ] || { echo "FAILED: $k"; fails=1; }; done
exit $fails
